const e = require('express');
const express = require('express');
const User = require('../models/users_model');
const jwt = require('jsonwebtoken');
const auth = require('../middlewares/auth');
const authRouter = express.Router();


authRouter.post('/api/signup', async(req, res) => {
    console.log(req.body)
    try {
        const {name, email, profilePic} = req.body;

        // If email exists, don't store the data
        let user = await User.findOne({email: email});

        if(!user) {
            user = new User({
                email: email,
                profilePic: profilePic,
                name: name,
            });
            user = await user.save();
        }
        //Signing our JWT with a secret key, usual to generated by running certain random code in the terminal, 
        // But this is not a serious software... 🙃

        const token = jwt.sign({id: user._id}, 'passwordKey'); 

        res.json({user, token});
    } catch (error) {
        res.status(500).json({error: e.message})
    }
}); 


authRouter.get('/', auth, async (req, res) => {
    // The req.id, is gotten from the auth middleware,
    // where the 'id' is added to the 'req' object,
     const user = await User.findById(req.id);
     res.json({user, token: req.token}); 
});

module.exports = authRouter;